export const up = (text) => text.toUpperCase();
export const low = (text) => text.toLowerCase();

export const renderResultType = (type) => {
  switch (type) {
    case "cgpaOfFour":
      return "CGPA (out of 4)";
    case "gpaOfFive":
      return "GPA (out of 5)";
    case "class":
      return "CLASS";
    case "division":
      return "DIVISION";
    default:
      return "N/A";
  }
};

export const renderGroup = (group) => {
  switch (group) {
    case "sc":
      return "SCIENCE";
    case "hu":
      return "HUMANITIES";
    case "bs":
      return "BUSINESS STUDIES";
    case "ba":
      return "BACHELOR OF ARTS";
    case "bss":
      return "BACHELOR OF SOCIAL SCIENCE";
    case "bbs":
      return "BACHELOR OF BUSINESS STUDIES";
    case "pol":
      return "BACHELOR OF SOCIAL SCIENCE (HONS) IN POLITICAL SCIENCE";
    case "ban":
      return "BACHELOR OF ARTS (HONS) IN BANGLA";
    case "hrm":
      return "HUMAN RESOURCE MANAGEMENT";
    case "co":
      return "COMPUTER OPERATION";
    default:
      return "N/A";
  }
};

export const renderExamination = (exam) => {
  switch (exam) {
    case "ssc":
      return "SECONDARY SCHOOL CERTIFICATION";
    case "hsc":
      return "HIGHER SECONDARY CERTIFICATE";
    case "degree":
      return "DEGREE PASS & CERTIFICATE COURSE";
    case "honours":
      return "BACHELOR OF HONOURS";
    case "bm":
      return "BUSINESS MANAGEMENT";
    case "bou":
      return "BANGLADESH OPEN UNIVERSITY";
    default:
      return exam.toUpperCase();
  }
};
export const renderGenderText = (gender, str) => {
  if (gender === "male" && Boolean(!str)) {
    return "He";
  } else if (gender === "female" && !str) {
    return "She";
  } else if (gender === "other" && !str) {
    return "He";
  } else if (gender === "male" && Boolean(str === true)) {
    return "him";
  } else if (gender === "female" && str) {
    return "her";
  } else {
    return "He/Her";
  }
  // switch (gender, str) {
  //   case "male":
  //     return "He";
  //   case "female":
  //     return "She";
  //   case "other":
  //     return "He";
  //   case 'male':
  //   case str: return 'him'
  //   case 'female':
  //   case str: return 'her'
  //   default:
  //     return "He";
  // }
};

export const renderGroupText = (group) => {
  switch (group) {
    case "sc":
    case "hu":
    case "bs":
      return "group";
    case "ba":
    case "bss":
    case "bbs":
      return "course";
    case "pol":
    case "ban":
      return "subject";
    case "hrm":
    case "co":
      return "trade";
    default:
      return "group";
  }
};

export const generateQRCodeText = (app) => {
  if (app)
    return `It is to certify that ${app.name.toUpperCase()}, father name: ${app.fatherName.toUpperCase()}, mother name: ${app.motherName.toUpperCase()}.${renderGenderText(
      app.gender
    )} has been passed ${app.lastExamName.toUpperCase()} on ${
      app.passingYear
    }. ${renderGenderText(app.gender)} bearing roll: ${
      app.roll
    }, registration: ${app.registration}. ${renderGenderText(
      app.gender
    )} has gained ${app.result} ${renderResultType(
      app.resultType
    )} on ${renderGroup(app.group)} ${renderGroupText(
      app.group
    )}. I wish your life best. This document is generated by Jibannagar Degree College. You may verify.`;
};
